// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOUzID1tzvJlpoEpSI94lhcah6Skk4-CE',
    appId: '1:184483986566:web:263f7016b588556b0b2507',
    messagingSenderId: '184483986566',
    projectId: 'lzzt-4cbd0',
    authDomain: 'lzzt-4cbd0.firebaseapp.com',
    storageBucket: 'lzzt-4cbd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZs14hCD8c6WNW3-LZDWhh4Rea69bWopE',
    appId: '1:184483986566:android:869ff0ca5e3c603f0b2507',
    messagingSenderId: '184483986566',
    projectId: 'lzzt-4cbd0',
    storageBucket: 'lzzt-4cbd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH0cD656_HD-weRr9kXOJYL9b2JA8Wi4o',
    appId: '1:184483986566:ios:b741cc5f70e8b29e0b2507',
    messagingSenderId: '184483986566',
    projectId: 'lzzt-4cbd0',
    storageBucket: 'lzzt-4cbd0.appspot.com',
    iosBundleId: 'com.example.lzzt',
  );
}
